services:
  db:
    image: mysql:latest
    volumes:
      - ./db_data-NOBU:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_root_password
      - db_password

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    ports:
      - 8000:80
    environment:
      PMA_HOST: db

secrets:
  db_password:
    # Password in plain text in this file!
    file: db_password.txt
  db_root_password:
    # Password in plain text in this file!
    file: db_root_password.txt
